run_test:
  image: julia:1.8
  script:
    - julia --project=@. -e 'import Pkg; Pkg.Registry.add(Pkg.RegistrySpec(url="https://github.com/SimeonEhrig/GitLabCIRegistry.git")); Pkg.test(; coverage = true)'
