run_test:
  image: julia:1.8
  script:
    # run first jobGenertor test, because the custom registry overwrites the default registry
    - cd jobGenerator
    - julia --project=. -e 'import Pkg; Pkg.test(; coverage = true)'
    - cd ..
    - julia --project=. -e 'import Pkg; Pkg.Registry.add(Pkg.RegistrySpec(url="https://github.com/SimeonEhrig/GitLabCIRegistry.git")); Pkg.test(; coverage = true)'
