name = "GitlabCIMain"
uuid = "86949938-77a9-419e-aff1-1b5d557cfdb2"
authors = ["Simeon Ehrig <s.ehrig@hzdr.de> and contributors"]
version = "1.0.0-DEV"

[deps]
Documenter = "e30172f5-a6a5-5a46-863b-614d45cd2de4"
GitLabCISub1 = "2df81c4e-c6cd-4631-b325-cacad6d6abac"
GitLabCISub2 = "0c825e4a-f476-45ea-8667-4d6a1b82536a"

[compat]
julia = "1"

[extras]
Test = "8dfed614-e22c-5e08-85e1-65c5234f0b40"

[targets]
test = ["Test"]
